Attribute VB_Name = "E_ColumnConstants"
'=== Date cutoff named range (for user input on Control sheet)
Public Const NAME_CUTOFF_DATE As String = "PT_CutoffDate"
Public Const NAME_USE_CUTOFF As String = "PT_UseCutoff"
' Initialize global column constants (should be declared at the top of the module)

'Summary tab columns
Global COL_STRATEGY_NUMBER As Long
Global COL_CREATE_DETAILED_TAB As Long
Global COL_OPEN_CODE_TAB As Long
Global COL_CODE_TEXT As Long
Global COL_FOLDER As Long
Global COL_STRATEGY_NAME As Long
Global COL_SYMBOL As Long
Global COL_SECTOR As Long
Global COL_TIMEFRAME As Long
Global COL_MARGIN As Long
Global COL_STATUS As Long ' Renamed for clarity
Global COL_ELIGIBILITY As Long
Global COL_SYMBOL_RANK As Long
Global COL_SECTOR_RANK As Long
Global COL_NEXT_OPT_DATE As Long
Global COL_LAST_OPT_DATE As Long
Global COL_OOS_BEGIN_DATE As Long
Global COL_LAST_DATE_ON_FILE As Long
Global COL_OOS_PERIOD As Long ' New column for OOS period
Global COL_EXPECTED_ANNUAL_PROFIT As Long
Global COL_ACTUAL_ANNUAL_PROFIT As Long
Global COL_RETURN_EFFICIENCY As Long
Global COL_EXPECTED_ANNUAL_RETURN As Long
Global COL_ACTUAL_ANNUAL_RETURN As Long
Global COL_RUN_MC As Long
Global COL_BACKTEST_MC As Long ' Monte Carlo Backtest Results
Global COL_CLOSEDTRADEMC As Long
Global COL_NOTIONAL_CAPITAL As Long
'Global COL_RISK_RUIN As Long
Global COL_LAST_12_MONTHS As Long
Global COL_IS_MONTE_CARLO As Long
Global COL_IS_OOS_MONTE_CARLO As Long
Global COL_IS_ANNUAL_SD_IS As Long
Global COL_IS_ANNUAL_SD_ISOOS As Long
Global COL_R_DD_12MONTH As Long
Global COL_R_DD_OOS As Long

Global COL_LONG_SHORT As Long

Global COL_PROFIT_FACTOR As Long
Global COL_PROFIT_LONG_FACTOR As Long
Global COL_PROFIT_SHORT_FACTOR As Long

Global COL_GROSS_LONG_NETPROFIT As Long
Global COL_GROSS_LONG_PROFIT As Long
Global COL_GROSS_LONG_LOSS As Long

Global COL_GROSS_SHORT_NETPROFIT As Long
Global COL_GROSS_SHORT_PROFIT As Long
Global COL_GROSS_SHORT_LOSS As Long

Global COL_BACKTEST_WINRATE As Long
Global COL_OOS_WINRATE As Long
Global COL_OVERALL_WINRATE As Long
Global COL_TRADES_PER_YEAR As Long
Global COL_PERCENT_TIME_IN_MARKET As Long
Global COL_AVG_TRADE_LENGTH As Long
Global COL_AVG_IS_OOS_TRADE As Long
Global COL_AVG_PROFIT_IS_OOS_TRADE As Long
Global COL_AVG_LOSS_IS_OOS_TRADE As Long
Global COL_LARGEST_WIN_IS_OOS_TRADE As Long
Global COL_LARGEST_LOSS_IS_OOS_TRADE As Long
Global COL_TOTAL_IS_PROFIT As Long
Global COL_TOTAL_IS_OSS_PROFIT As Long
Global COL_ANNUALIZED_NET_PROFIT_IS_OOS As Long
Global COL_WORST_BACKTEST_DRAWDOWN As Long
Global COL_WORST_IS_OOS_DRAWDOWN As Long
Global COL_AVG_BACKTEST_DRAWDOWN As Long
Global COL_AVG_IS_OOS_DRAWDOWN As Long
Global COL_MAX_OOS_DRAWDOWN As Long
Global COL_AVG_OOS_DRAWDOWN As Long
Global COL_MAX_DRAWDOWN_LAST_12_MONTHS As Long
Global COL_PROFIT_LAST_1_MONTH As Long
Global COL_PROFIT_LAST_3_MONTHS As Long
Global COL_PROFIT_LAST_6_MONTHS As Long
Global COL_PROFIT_LAST_9_MONTHS As Long
Global COL_PROFIT_LAST_12_MONTHS As Long
Global COL_PROFIT_SINCE_OOS_START As Long
Global COL_COUNT_PROFIT_MONTHS As Long
Global COL_EFFICIENCY_LAST_1_MONTH As Long
Global COL_EFFICIENCY_LAST_3_MONTHS As Long
Global COL_EFFICIENCY_LAST_6_MONTHS As Long
Global COL_EFFICIENCY_LAST_9_MONTHS As Long
Global COL_EFFICIENCY_LAST_12_MONTHS As Long
Global COL_EFFICIENCY_SINCE_OOS_START As Long
Global COL_INCUBATION_STATUS As Long
Global COL_INCUBATION_DATE As Long
Global COL_QUITTING_STATUS As Long
Global COL_QUITTING_DATE As Long
Global COL_CURRENT_POSITION As Long

Global COL_WF_IN_OUT As Long
Global COL_ANCHORED As Long
Global COL_FITNESS As Long
Global COL_SESSION As Long
Global COL_DATA2_SYMBOL As Long
Global COL_DATA2_TIMEFRAME As Long
Global COL_DATA3_SYMBOL As Long
Global COL_DATA3_TIMEFRAME As Long
Global COL_START_DATE As Long
Global COL_TRADINGDAYS_IS As Long
Global COL_TRADINGDAYS_ISOOS As Long
Global COL_SHARPE_IS As Long
Global COL_SHARPE_ISOOS As Long



'Portfolio tab columns
Global COL_PORT_STRATEGYCOUNT As Long
Global COL_PORT_STRATEGY_NUMBER As Long
Global COL_PORT_CREATE_DETAILED_TAB As Long
Global COL_PORT_OPEN_CODE_TAB As Long
Global COL_PORT_CODE_TEXT As Long
Global COL_PORT_FOLDER As Long
Global COL_PORT_STRATEGY_NAME As Long
Global COL_PORT_CONTRACTS As Long
Global COL_PORT_SYMBOL As Long
Global COL_PORT_TIMEFRAME As Long
Global COL_PORT_SECTOR As Long
Global COL_PORT_TYPE As Long
Global COL_PORT_HORIZON As Long
Global COL_PORT_LONGSHORT As Long

Global COL_PORT_MARGIN As Long
Global COL_PORT_CONTRACT_SIZE As Long
Global COL_PORT_EST_CONTRACTS As Long



Global COL_PORT_STATUS As Long
Global COL_PORT_ELIGIBILITY As Long
Global COL_PORT_NEXT_OPT_DATE As Long
Global COL_PORT_LAST_OPT_DATE As Long
Global COL_PORT_LAST_DATE_ON_FILE As Long
Global COL_PORT_EXPECTED_ANNUAL_PROFIT As Long
Global COL_PORT_ACTUAL_ANNUAL_PROFIT As Long
Global COL_PORT_NOTIONAL_CAPITAL As Long
Global COL_PORT_TRADES_PER_YEAR As Long
Global COL_PORT_PERCENT_TIME_IN_MARKET As Long
Global COL_PORT_AVG_TRADE_LENGTH As Long


Global COL_PORT_IS_ANNUAL_SD_IS As Long
Global COL_PORT_IS_ANNUAL_SD_ISOOS As Long
Global COL_PORT_AVG_IS_OOS_TRADE As Long
Global COL_PORT_AVG_PROFIT_IS_OOS_TRADE As Long
Global COL_PORT_AVG_LOSS_IS_OOS_TRADE As Long
Global COL_PORT_LARGEST_WIN_IS_OOS_TRADE As Long
Global COL_PORT_LARGEST_LOSS_IS_OOS_TRADE As Long
Global COL_PORT_AVG_IS_OOS_DRAWDOWN As Long
Global COL_PORT_MAX_IS_OOS_DRAWDOWN As Long
Global COL_PORT_MAX_DRAWDOWN_LAST_12_MONTHS As Long
Global COL_PORT_PROFIT_LAST_1_MONTH As Long
Global COL_PORT_PROFIT_LAST_3_MONTHS As Long
Global COL_PORT_PROFIT_LAST_6_MONTHS As Long
Global COL_PORT_PROFIT_LAST_9_MONTHS As Long
Global COL_PORT_PROFIT_LAST_12_MONTHS As Long
Global COL_PORT_PROFIT_SINCE_OOS_START As Long
Global COL_PORT_COUNT_PROFIT_MONTHS As Long
Global COL_PORT_ATR_LAST_1_MONTH As Long
Global COL_PORT_ATR_LAST_3_MONTHS As Long
Global COL_PORT_ATR_LAST_6_MONTHS As Long
Global COL_PORT_ATR_LAST_12_MONTHS As Long
Global COL_PORT_ATR_LAST_24_MONTHS As Long
Global COL_PORT_ATR_LAST_60_MONTHS As Long
Global COL_PORT_ATR_ALL_DATA As Long
Global COL_PORT_CURRENT_POSITION As Long

'Strategy tab columns
Global COL_STRAT_STRATEGY_NUMBER As Long
Global COL_STRAT_STATUS As Long
Global COL_STRAT_STRATEGY_NAME As Long
Global COL_STRAT_CONTRACTS As Long
Global COL_STRAT_SYMBOL As Long
Global COL_STRAT_TIMEFRAME As Long
Global COL_STRAT_TYPE As Long
Global COL_STRAT_HORIZON As Long
Global COL_STRAT_OTHER As Long
Global COL_STRAT_CLOSEDTRADEMC As Long
Global COL_STRAT_FOLDER As Long
Global COL_STRAT_NOTES As Long



Global COL_BACKSTRAT_DATE As Long
Global COL_BACKSTRAT_DAILY_PL As Long
Global COL_BACKSTRAT_CUM_PL As Long
Global COL_BACKSTRAT_DRAWDOWN As Long
Global COL_BACKSTRAT_YEAR As Long
Global COL_BACKSTRAT_MONTH As Long
Global COL_BACKSTRAT_WEEK As Long






' Routine to manually initialize all global column constants
Sub InitializeColumnConstantsManually()
    ' Manually assign the column numbers
    
    
    COL_STRATEGY_NUMBER = 1
    COL_CREATE_DETAILED_TAB = COL_STRATEGY_NUMBER + 1
    COL_OPEN_CODE_TAB = COL_CREATE_DETAILED_TAB + 1
    COL_CODE_TEXT = COL_OPEN_CODE_TAB + 1
    COL_FOLDER = COL_CODE_TEXT + 1
    COL_STRATEGY_NAME = COL_FOLDER + 1
    COL_SYMBOL = COL_STRATEGY_NAME + 1
    COL_SECTOR = COL_SYMBOL + 1
    COL_TIMEFRAME = COL_SECTOR + 1
    COL_MARGIN = COL_TIMEFRAME + 1
    COL_STATUS = COL_MARGIN + 1
    COL_ELIGIBILITY = COL_STATUS + 1
    COL_SYMBOL_RANK = COL_ELIGIBILITY + 1
    COL_SECTOR_RANK = COL_SYMBOL_RANK + 1
    COL_LAST_12_MONTHS = COL_SECTOR_RANK + 1
    COL_NEXT_OPT_DATE = COL_LAST_12_MONTHS + 1
    COL_LAST_OPT_DATE = COL_NEXT_OPT_DATE + 1
    COL_OOS_BEGIN_DATE = COL_LAST_OPT_DATE + 1
    COL_LAST_DATE_ON_FILE = COL_OOS_BEGIN_DATE + 1
    COL_EXPECTED_ANNUAL_PROFIT = COL_LAST_DATE_ON_FILE + 1
    COL_ACTUAL_ANNUAL_PROFIT = COL_EXPECTED_ANNUAL_PROFIT + 1
    COL_RETURN_EFFICIENCY = COL_ACTUAL_ANNUAL_PROFIT + 1
    COL_EXPECTED_ANNUAL_RETURN = COL_RETURN_EFFICIENCY + 1
    COL_ACTUAL_ANNUAL_RETURN = COL_EXPECTED_ANNUAL_RETURN + 1
    COL_PROFIT_LAST_1_MONTH = COL_ACTUAL_ANNUAL_RETURN + 1
    COL_PROFIT_LAST_3_MONTHS = COL_PROFIT_LAST_1_MONTH + 1
    COL_PROFIT_LAST_6_MONTHS = COL_PROFIT_LAST_3_MONTHS + 1
    COL_PROFIT_LAST_9_MONTHS = COL_PROFIT_LAST_6_MONTHS + 1
    COL_PROFIT_LAST_12_MONTHS = COL_PROFIT_LAST_9_MONTHS + 1
    COL_PROFIT_SINCE_OOS_START = COL_PROFIT_LAST_12_MONTHS + 1
    COL_COUNT_PROFIT_MONTHS = COL_PROFIT_SINCE_OOS_START + 1
    COL_INCUBATION_STATUS = COL_COUNT_PROFIT_MONTHS + 1
    COL_INCUBATION_DATE = COL_INCUBATION_STATUS + 1
    COL_QUITTING_STATUS = COL_INCUBATION_DATE + 1
    COL_QUITTING_DATE = COL_QUITTING_STATUS + 1
    
    COL_CURRENT_POSITION = COL_QUITTING_DATE + 1
    
    COL_NOTIONAL_CAPITAL = COL_CURRENT_POSITION + 1
    COL_RUN_MC = COL_NOTIONAL_CAPITAL + 1
    COL_BACKTEST_MC = COL_RUN_MC + 1
    COL_CLOSEDTRADEMC = COL_BACKTEST_MC + 1
    COL_IS_MONTE_CARLO = COL_CLOSEDTRADEMC + 1
    COL_IS_OOS_MONTE_CARLO = COL_IS_MONTE_CARLO + 1
    
    COL_LONG_SHORT = COL_IS_OOS_MONTE_CARLO + 1
    
    COL_PROFIT_FACTOR = COL_LONG_SHORT + 1
    COL_PROFIT_LONG_FACTOR = COL_PROFIT_FACTOR + 1
    COL_PROFIT_SHORT_FACTOR = COL_PROFIT_LONG_FACTOR + 1
    
    COL_GROSS_LONG_NETPROFIT = COL_PROFIT_SHORT_FACTOR + 1
    COL_GROSS_LONG_PROFIT = COL_GROSS_LONG_NETPROFIT + 1
    COL_GROSS_LONG_LOSS = COL_GROSS_LONG_PROFIT + 1
    
    COL_GROSS_SHORT_NETPROFIT = COL_GROSS_LONG_LOSS + 1
    COL_GROSS_SHORT_PROFIT = COL_GROSS_SHORT_NETPROFIT + 1
    COL_GROSS_SHORT_LOSS = COL_GROSS_SHORT_PROFIT + 1
    
    
    
    COL_IS_ANNUAL_SD_IS = COL_GROSS_SHORT_LOSS + 1
    COL_IS_ANNUAL_SD_ISOOS = COL_IS_ANNUAL_SD_IS + 1
    COL_R_DD_12MONTH = COL_IS_ANNUAL_SD_ISOOS + 1
    COL_R_DD_OOS = COL_R_DD_12MONTH + 1
    COL_BACKTEST_WINRATE = COL_R_DD_OOS + 1
    COL_OOS_WINRATE = COL_BACKTEST_WINRATE + 1
    COL_OVERALL_WINRATE = COL_OOS_WINRATE + 1
    COL_TRADES_PER_YEAR = COL_OVERALL_WINRATE + 1
    COL_PERCENT_TIME_IN_MARKET = COL_TRADES_PER_YEAR + 1
    COL_AVG_TRADE_LENGTH = COL_PERCENT_TIME_IN_MARKET + 1
    COL_AVG_IS_OOS_TRADE = COL_AVG_TRADE_LENGTH + 1
    COL_AVG_PROFIT_IS_OOS_TRADE = COL_AVG_IS_OOS_TRADE + 1
    COL_AVG_LOSS_IS_OOS_TRADE = COL_AVG_PROFIT_IS_OOS_TRADE + 1
    COL_LARGEST_WIN_IS_OOS_TRADE = COL_AVG_LOSS_IS_OOS_TRADE + 1
    COL_LARGEST_LOSS_IS_OOS_TRADE = COL_LARGEST_WIN_IS_OOS_TRADE + 1
    COL_TOTAL_IS_PROFIT = COL_LARGEST_LOSS_IS_OOS_TRADE + 1
    COL_TOTAL_IS_OSS_PROFIT = COL_TOTAL_IS_PROFIT + 1
    COL_ANNUALIZED_NET_PROFIT_IS_OOS = COL_TOTAL_IS_OSS_PROFIT + 1
    COL_WORST_BACKTEST_DRAWDOWN = COL_ANNUALIZED_NET_PROFIT_IS_OOS + 1
    COL_WORST_IS_OOS_DRAWDOWN = COL_WORST_BACKTEST_DRAWDOWN + 1
    COL_AVG_BACKTEST_DRAWDOWN = COL_WORST_IS_OOS_DRAWDOWN + 1
    COL_AVG_IS_OOS_DRAWDOWN = COL_AVG_BACKTEST_DRAWDOWN + 1
    COL_MAX_OOS_DRAWDOWN = COL_AVG_IS_OOS_DRAWDOWN + 1
    COL_AVG_OOS_DRAWDOWN = COL_MAX_OOS_DRAWDOWN + 1
    COL_MAX_DRAWDOWN_LAST_12_MONTHS = COL_AVG_OOS_DRAWDOWN + 1

    COL_EFFICIENCY_LAST_1_MONTH = COL_MAX_DRAWDOWN_LAST_12_MONTHS + 1
    COL_EFFICIENCY_LAST_3_MONTHS = COL_EFFICIENCY_LAST_1_MONTH + 1
    COL_EFFICIENCY_LAST_6_MONTHS = COL_EFFICIENCY_LAST_3_MONTHS + 1
    COL_EFFICIENCY_LAST_9_MONTHS = COL_EFFICIENCY_LAST_6_MONTHS + 1
    COL_EFFICIENCY_LAST_12_MONTHS = COL_EFFICIENCY_LAST_9_MONTHS + 1
    COL_EFFICIENCY_SINCE_OOS_START = COL_EFFICIENCY_LAST_12_MONTHS + 1
    
    COL_WF_IN_OUT = COL_EFFICIENCY_SINCE_OOS_START + 1
    COL_ANCHORED = COL_WF_IN_OUT + 1
    COL_FITNESS = COL_ANCHORED + 1
    COL_SESSION = COL_FITNESS + 1
    COL_OOS_PERIOD = COL_SESSION + 1 ' Adjust the number according to your needs
    COL_DATA2_SYMBOL = COL_OOS_PERIOD + 1
    COL_DATA2_TIMEFRAME = COL_DATA2_SYMBOL + 1
    COL_DATA3_SYMBOL = COL_DATA2_TIMEFRAME + 1
    COL_DATA3_TIMEFRAME = COL_DATA3_SYMBOL + 1
    COL_START_DATE = COL_DATA3_TIMEFRAME + 1
    COL_TRADINGDAYS_IS = COL_START_DATE + 1
    COL_TRADINGDAYS_ISOOS = COL_TRADINGDAYS_IS + 1
    COL_SHARPE_IS = COL_TRADINGDAYS_ISOOS + 1
    COL_SHARPE_ISOOS = COL_SHARPE_IS + 1

    
        
        
        
    'PORTFOLIO TAB CONSTANTS
    COL_PORT_STRATEGYCOUNT = 1
    COL_PORT_STRATEGY_NUMBER = COL_PORT_STRATEGYCOUNT + 1
    COL_PORT_CREATE_DETAILED_TAB = COL_PORT_STRATEGY_NUMBER + 1
    COL_PORT_OPEN_CODE_TAB = COL_PORT_CREATE_DETAILED_TAB + 1
    COL_PORT_CODE_TEXT = COL_PORT_OPEN_CODE_TAB + 1
    COL_PORT_FOLDER = COL_PORT_CODE_TEXT + 1
    COL_PORT_STRATEGY_NAME = COL_PORT_FOLDER + 1
    COL_PORT_CONTRACTS = COL_PORT_STRATEGY_NAME + 1
    COL_PORT_SYMBOL = COL_PORT_CONTRACTS + 1
    COL_PORT_TIMEFRAME = COL_PORT_SYMBOL + 1
    COL_PORT_SECTOR = COL_PORT_TIMEFRAME + 1
    COL_PORT_TYPE = COL_PORT_SECTOR + 1
    COL_PORT_HORIZON = COL_PORT_TYPE + 1
    COL_PORT_LONGSHORT = COL_PORT_HORIZON + 1
    COL_PORT_MARGIN = COL_PORT_LONGSHORT + 1
    
    COL_PORT_CONTRACT_SIZE = COL_PORT_MARGIN + 1
    COL_PORT_EST_CONTRACTS = COL_PORT_CONTRACT_SIZE + 1
    
    
    COL_PORT_STATUS = COL_PORT_EST_CONTRACTS + 1
    COL_PORT_ELIGIBILITY = COL_PORT_STATUS + 1
    COL_PORT_NEXT_OPT_DATE = COL_PORT_ELIGIBILITY + 1
    COL_PORT_LAST_OPT_DATE = COL_PORT_NEXT_OPT_DATE + 1
    COL_PORT_LAST_DATE_ON_FILE = COL_PORT_LAST_OPT_DATE + 1
    COL_PORT_CURRENT_POSITION = COL_PORT_LAST_DATE_ON_FILE + 1
    
    
    COL_PORT_EXPECTED_ANNUAL_PROFIT = COL_PORT_CURRENT_POSITION + 1
    COL_PORT_ACTUAL_ANNUAL_PROFIT = COL_PORT_EXPECTED_ANNUAL_PROFIT + 1
    COL_PORT_NOTIONAL_CAPITAL = COL_PORT_ACTUAL_ANNUAL_PROFIT + 1
    COL_PORT_IS_ANNUAL_SD_IS = COL_PORT_NOTIONAL_CAPITAL + 1
    COL_PORT_IS_ANNUAL_SD_ISOOS = COL_PORT_IS_ANNUAL_SD_IS + 1
    COL_PORT_TRADES_PER_YEAR = COL_PORT_IS_ANNUAL_SD_ISOOS + 1
    COL_PORT_PERCENT_TIME_IN_MARKET = COL_PORT_TRADES_PER_YEAR + 1
    COL_PORT_AVG_TRADE_LENGTH = COL_PORT_PERCENT_TIME_IN_MARKET + 1
    COL_PORT_AVG_IS_OOS_TRADE = COL_PORT_AVG_TRADE_LENGTH + 1
    COL_PORT_AVG_PROFIT_IS_OOS_TRADE = COL_PORT_AVG_IS_OOS_TRADE + 1
    COL_PORT_AVG_LOSS_IS_OOS_TRADE = COL_PORT_AVG_PROFIT_IS_OOS_TRADE + 1
    COL_PORT_LARGEST_WIN_IS_OOS_TRADE = COL_PORT_AVG_LOSS_IS_OOS_TRADE + 1
    COL_PORT_LARGEST_LOSS_IS_OOS_TRADE = COL_PORT_LARGEST_WIN_IS_OOS_TRADE + 1
    COL_PORT_MAX_IS_OOS_DRAWDOWN = COL_PORT_LARGEST_LOSS_IS_OOS_TRADE + 1
    COL_PORT_AVG_IS_OOS_DRAWDOWN = COL_PORT_MAX_IS_OOS_DRAWDOWN + 1
    COL_PORT_MAX_DRAWDOWN_LAST_12_MONTHS = COL_PORT_AVG_IS_OOS_DRAWDOWN + 1
    
    COL_PORT_PROFIT_LAST_1_MONTH = COL_PORT_MAX_DRAWDOWN_LAST_12_MONTHS + 1
    COL_PORT_PROFIT_LAST_3_MONTHS = COL_PORT_PROFIT_LAST_1_MONTH + 1
    COL_PORT_PROFIT_LAST_6_MONTHS = COL_PORT_PROFIT_LAST_3_MONTHS + 1
    COL_PORT_PROFIT_LAST_9_MONTHS = COL_PORT_PROFIT_LAST_6_MONTHS + 1
    COL_PORT_PROFIT_LAST_12_MONTHS = COL_PORT_PROFIT_LAST_9_MONTHS + 1
    COL_PORT_PROFIT_SINCE_OOS_START = COL_PORT_PROFIT_LAST_12_MONTHS + 1
    COL_PORT_COUNT_PROFIT_MONTHS = COL_PORT_PROFIT_SINCE_OOS_START + 1
    COL_PORT_ATR_LAST_1_MONTH = COL_PORT_COUNT_PROFIT_MONTHS + 1
    COL_PORT_ATR_LAST_3_MONTHS = COL_PORT_ATR_LAST_1_MONTH + 1
    COL_PORT_ATR_LAST_6_MONTHS = COL_PORT_ATR_LAST_3_MONTHS + 1
    COL_PORT_ATR_LAST_12_MONTHS = COL_PORT_ATR_LAST_6_MONTHS + 1
    COL_PORT_ATR_LAST_24_MONTHS = COL_PORT_ATR_LAST_12_MONTHS + 1
    COL_PORT_ATR_LAST_60_MONTHS = COL_PORT_ATR_LAST_24_MONTHS + 1
    COL_PORT_ATR_ALL_DATA = COL_PORT_ATR_LAST_60_MONTHS + 1
    
    
    
    COL_STRAT_STRATEGY_NUMBER = 1
    COL_STRAT_STATUS = COL_STRAT_STRATEGY_NUMBER + 1
    COL_STRAT_STRATEGY_NAME = COL_STRAT_STATUS + 1
    COL_STRAT_CONTRACTS = COL_STRAT_STRATEGY_NAME + 1
    COL_STRAT_SYMBOL = COL_STRAT_CONTRACTS + 1
    COL_STRAT_TIMEFRAME = COL_STRAT_SYMBOL + 1
    COL_STRAT_TYPE = COL_STRAT_TIMEFRAME + 1
    COL_STRAT_HORIZON = COL_STRAT_TYPE + 1
    COL_STRAT_OTHER = COL_STRAT_HORIZON + 1
    COL_STRAT_CLOSEDTRADEMC = COL_STRAT_OTHER + 1
    COL_STRAT_FOLDER = COL_STRAT_CLOSEDTRADEMC + 1
    COL_STRAT_NOTES = COL_STRAT_FOLDER + 1
    
    
   
    
    COL_BACKSTRAT_DATE = 35
    COL_BACKSTRAT_DAILY_PL = COL_BACKSTRAT_DATE + 1
    COL_BACKSTRAT_CUM_PL = COL_BACKSTRAT_DAILY_PL + 1
    COL_BACKSTRAT_DRAWDOWN = COL_BACKSTRAT_CUM_PL + 1
    COL_BACKSTRAT_YEAR = COL_BACKSTRAT_DRAWDOWN + 1
    COL_BACKSTRAT_MONTH = COL_BACKSTRAT_YEAR + 1
    COL_BACKSTRAT_WEEK = COL_BACKSTRAT_MONTH + 1

          
End Sub
